name: Front-end deploy

on:
  push:
    branches: [ main ]
    paths: [ 'static/**' ]        # trigger only when site files change

permissions:
  id-token: write                 
  contents: read

env:
  AWS_REGION: il-central-1
  ROLE_ARN: arn:aws:iam::108782097005:role/gh-actions-deploy
  BUCKET: my-resume-site-lior-il
  CF_DIST: E1W2FC68COD9BW         # CloudFront distribution ID

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS creds (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.ROLE_ARN }}
        aws-region:     ${{ env.AWS_REGION }}

    - name: Sync static/ to S3
      run: |
        aws s3 sync static/ s3://$BUCKET --delete \
          --cache-control "max-age=60,must-revalidate"

    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation \
          --distribution-id $CF_DIST \
          --paths "/*"
