name: Deploy static site to S3

on:
  push:
    branches: [ main ]
    paths: [ 'static/**', '.github/workflows/deploy.yml' ]  # re-run if workflow changes
  workflow_dispatch:                                        # manual trigger

permissions:
  id-token: write   # required for OIDC
  contents: read    # checkout code

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ──────────────────────────────────────────────
      #  Assume the gh-actions-deploy role via OIDC
      # ──────────────────────────────────────────────
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region:     ${{ secrets.AWS_REGION }}

      # ──────────────────────────────────────────────
      #  Upload updated files to the S3 bucket
      # ──────────────────────────────────────────────
      - name: Sync static/ to S3
        run: |
          aws s3 sync static/ "s3://${{ secrets.BUCKET }}/" --delete \
            --cache-control "max-age=60,must-revalidate"

      # ──────────────────────────────────────────────
      #  Invalidate CloudFront so new assets show up
      # ──────────────────────────────────────────────
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CF_DIST }} \
            --paths "/index.html" "/index.js" "/style.css"
